export const FreelancerData = {
    freelancer: [{
            id: 1,
            shortDescription: "Highly Skilled .Net Developer",
            completedProject: 19,
            dispute: 2,
            hourlyRate: "24",
            introduction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        },
        {
            id: 2,
            shortDescription: "React Expert 5 years",
            completedProject: 19,
            dispute: 2,
            hourlyRate: "24",
            introduction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        },
        {
            id: 3,
            shortDescription: "Good Designer",
            completedProject: 1,
            dispute: 2,
            hourlyRate: "14",
            introduction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        },
        {
            id: 4,
            shortDescription: "The best skill with sincerity",
            completedProject: 19,
            dispute: 0,
            hourlyRate: "24",
            introduction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        },
        {
            id: 5,
            shortDescription: "Passion, skill, and Experience",
            completedProject: 7,
            dispute: 0,
            hourlyRate: "24",
            introduction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        },


    ],
}

export const MyFreelancerData = {
    project: [{
            id: 1,
            projectNo: "20910000192001",
            projectCreatedDate: "2018.08.02",
            currency: "US$",
            projectAmount: "24,000",
            projectTitle: "Homepage design for 40 pages",
            projectContents: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 7,
            valid: 30,
            remain: 1,
            requiredSkillIds: [1, 2, 4, 5],
            projectType: "Milestone Project",
            projectStatus: "ongoing",
            participants: [1, 2, 5],
            businessCateogry: "design",
            totalMilestones: 3,
            timeLimit: "30hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "5years",
        },
        {
            id: 2,
            projectNo: "19918240192685",
            projectCreatedDate: "2018.09.02",
            currency: "US$",
            projectAmount: "10.00",
            projectTitle: "Accounting help regualr work for 2 days per week",
            projectContents: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 9,
            valid: 30,
            remain: 9,
            requiredSkillIds: [2, 3, 4, 5, 1, 6],
            projectType: "Hourly",
            projectStatus: "Completed",
            participants: [1, 3, 5],
            totalMilestones: 3,
            timeLimit: "45hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "OK",
            japaneseLevel: "Native",
            experienceLevel: "15years",
        },
        {
            id: 5,
            projectNo: "20918240192384",
            projectCreatedDate: "2018.09.02",
            currency: "USD",
            projectAmount: "25",
            projectTitle: "Angular and Backend with C# Mobile Developmenet",
            projectContents: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 2,
            valid: 30,
            remain: 3,
            requiredSkillIds: [1, 3, 4, 5],
            projectType: "Milestone Project",
            projectStatus: "ongoing",
            participants: [1, 2, 6],
            businessCateogry: "Legal Assistant",
            totalMilestones: 3,
            timeLimit: "50hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "5years",

        },
        {
            id: 4,
            projectNo: "20918240192005",
            projectCreatedDate: "2018.09.02",
            currency: "JPY",
            projectAmount: "10,000",
            projectTitle: "Looking for a legal assistant",
            projectContents: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 33,
            valid: 30,
            remain: 3,
            requiredSkillIds: [1, 2, 3, 4],
            projectType: "Hourly & Office",
            projectStatus: "Completed",
            participants: [1, 2, 4],
            businessCateogry: "Legal Assistant",
            totalMilestones: 3,
            timeLimit: "10hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "5years",
        },
       
        {
            id: 7,
            projectNo: "90918240198080",
            projectCreatedDate: "2018.09.02",
            currency: "USD",
            projectAmount: "9,000",
            projectTitle: "My House Logo design",
            projectContents: "Lorem Ipsum is the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 2,
            valid: 0,
            remain: 3,
            requiredSkillIds: [2, 3, 4, 6],
            projectType: "InOffice",
            projectStatus: "Initial Stage",
            participants: [1, 2, 5],
            businessCateogry: "Design",
            totalMilestones: 3,
            timeLimit: "30hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$5.00~$25.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "10years",

        },
        {
            id: 6,
            projectNo: "20918240191111",
            projectCreatedDate: "2018.09.02",
            currency: "USD",
            projectAmount: "3,000",
            projectTitle: "My Photo design",
            projectContents: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 2,
            valid: 0,
            remain: 3,
            requiredSkillIds: [1, 3, 4, 5],
            projectType: "Hourly & Office",
            projectStatus: "Final Contest",
            participants: [1, 2, 5],
            businessCateogry: "Design",
            totalMilestones: 3,
            timeLimit: "44hours per week",
            clientId: 3,
            developerType: "team",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "5years",

        },

        {
            id: 3,
            projectNo: "20918240192005",
            projectCreatedDate: "2018.09.02",
            currency: "JPY",
            projectAmount: "10,000",
            projectTitle: "2 days in Office Looking for a legal assistant",
            projectContents: "Hourly and Office printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,n an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
            applicants: 33,
            valid: 30,
            remain: 3,
            requiredSkillIds: [1, 2, 3, 4],
            projectType: "Hourly",
            projectStatus: "Completed",
            participants: [1, 2, 4],
            businessCateogry: "Legal Assistant",
            totalMilestones: 3,
            timeLimit: "30hours per week",
            clientId: 3,
            developerType: "Individual",
            hourlyRate: "$10.00~$15.00",
            englishLevel: "Fluent",
            japaneseLevel: "Native",
            experienceLevel: "5years",
        },
    ],
    contest: [{
            id: 1,
            award1: "3,000",
            award2: "2,500",
            award3: "1,000"
        },
        {
            id: 2,
            award1: "5,000",
            award2: "500",
            award3: ""
        }
    ],
}