
export const LANGAUGE_CONST = "LANGAUGE_CONST";
export const ROUTE_CONST = "ROUTE_CONST";
export const PROJECT_SELECT_CONST = "PROJECT_SELECT_CONST";
export const PROJECT_CONFIRMATION_DATA_CONST = "PROJECT_CONFIRMATION_DATA_CONST";

