export const MainTextEnglish = {
    ACCOUNTING_TEXT: "Accounting",
    ADD_MORE_SERVICES: "Add More Services",
    ADMIN: "Admin",
    ALL_FREELANCERS: "All Freelancers",

    ALL_PROJECTS: "All Projects",
    ALL_PROJECTS_SUB: "Find projects, that most suitable for you",
    APP_DEVELOPMENT: "App/Software",
    APPLICANTS_TEXT: "Applicants",
    AWARDS_TEXT: "Awards",
    BANNER_MAIN_FIRST: "The Most Effective Way of",
    BANNER_MAIN_SECOND: "Managing Your Project.",
    BANNER_MAIN_THIRD: "정글웍스에서는 프로젝트는 물론 시간별 고용이 가능하여  고용인에게는 업무효율의 극대화를 프리랜서에게는 시간의 가치를 제공합니다.",
    BANNER_MAIN_FORTH: "정글토크에서 제공하는 프로젝트 관리 프로그램을 활용하여 실시간 채팅 및 파일 업무관리 관리 다양한 관리툴을 무료로 사용하실수 있습니다.",
    BLIND_TEXT: "Blind",
    CAPTURED_VIEW: "Captured View",
    CANCEL_TEXT: "Cancel",
    CANDIDATES_TEXT: "Candidate",
    CATEGORY_TEXT: "Category",
    COMPLETED_TEXT: "Completed",
    CONFIRM_CONTEST: "Contest Confirmation!",
    CONFIRM_PROJECT: "Project Confirmation! ",
    CONFIRM_MILESTONE: "Milestone Confirmation!",
    CONFIRM_INOFFICE: "In Office Confirmation!",
    CONFIRM_HOURLY: "Hourly Confirmation!",
    CONTEST: "Contest",
    CONTEST_DETAIL: "Contest Detail",
    CONTACT_US: "Contact Us",
    CLIENT_INFO: "Client Information",
    COMMUNITY: "Community",
    CHANNEL: "Channel",
    COMMUNICATION_MANAGER: "Communication Manager",
    CONTRACT_HISTORY: "Contract History",
    CREATE_A_NEW_POST: "Create a new post",
    CUSTOMER_SERVICE: "Customer Service",
    DAYS_TEXT: "Days",
    DAYS_LEFT: "days left",
    DESIGN_CONTEST: "Design Contest",
    DESIGN_TEXT: "Design",
    DEACTIVATE_TEXT: "Deactivate",
    DISPUTE: "Dispute",
    DUE_DATE: "Due Date",
    ENGLISH: "English",
    ENGINEERING_TEXT: "Engineering",
    END_SOON: "End Soon",
    EVALUATION: "Evaluation",
    EXTEND_DUE_DATE: "Extend Due Date",
    FEEDBACK: "Feedback & Claims",
    FLEXIBILITY_FIRST: "시간제 그리고 상주업무 또는 이를 혼합하여 업무를 협의할수 있습니다.",
    FLEXIBILITY_SECOND: "외부 프리랜서는 물론 기존의 근무자를 본 시스템에 적용하여 유연하게 재택근무와 내부근무를 동시에 관리할수 있습니다.",
    FLEXIBILITY_TITLE: "More Flexibility",
    HEADHUNTING_MANAGER: "Headhunting Manager",
    HELP_CENTER: "Help Center",
    HELP_DETAIL: "Help Center",
    HIGH_BUDGET: "High Budget",
    HOW_IT_WORKS: "How it works",
    HOURLYNOFFICE: "Hourly & In Office",
    HOURLY_TEXT: "Hourly",
    HOURLY_REPORT: "Hourly Report",
    HOURLY_DETAIL: "Hourly Detail",
    HOURLY_WORK: "Hourly Work",
    HOURLY_VIEW:"Hourly View",
    INTERNATIONAL_TRADE: "International Trade",
    IN_OFFICE: "In Office",
    IN_OFFICE_DETAIL: "In Office Detail",
    INVOICE: "Invoice",
    INVOICE_DETAIL: "Invoice Detail",
    JAPANESE: "日本語",
    JOBS_NEARBY: "Jobs Nearby",
    KOREAN: "한국어",
    FREELANCER: "Freelancer",
    FREELANCER_REGISTRATION: "Freelancer Registation",
    LANGAUGE: "Langauge",
    LAST_ACTIVITY: "Last Activity",
    LEGAL_ASSITANCE: "Legal Assistant",
    LOGO_CONTEST: "Logo Contest",
    LOGIN: "Login",
    LOW_BUDGET: "Low Budget",
    MARKETING_TEXT: "Marketing",
    MILESTONE_DETAIL: "Milestone Detail",
    MILESTONE_TEXT: "Milestone",
    MILESTONE_VIEW:"Milestone View",
    MILESTONE_REPORT:"Milestone Report",
    MY_CLIENT: "My Client",
    MY_CREDIT: "My Credit",
    MY_COUPON: "My Coupon",
    MY_CONTEST: "My Contests",
    MY_FREELANCERS: "My Freelancers",
    MY_PROJECT: "My Project",
    MY_PROJECTS: "My Projects",
    MY_PROPOSAL: "My Proposals",
    MY_REGION: "My Region",
    MY_REPORTS: "My Report",
    ONGOING_PROJECT: "Ongoing Project",
    PHOTO_VIDEO: "Video/Photo Edit",
    PACKAGE_DESIGN: "Package Design",
    PAYMENT_CONFIRMATION_TYPE: "Payment Confirmation",
    PLANNING: "Writing",
    PREFERRED_DESIGN: "Preferrence",
    PRIVATE_TEXT: "Private",
    PROFESSION_TEXT: "Profession",
    PROJECT: "Project",
    PROJECT_TITLE: "Project Title",
    PROJECT_TYPE: "Project Type",
    PROJECT_BLOG: "Project Inquiry",
    PROJECT_BUDGET: "Project Budget",
    PROJECT_NO: "Project No.",
    PROMOTION_TEXT: "Promotion",
    POST_A_PROJECT: "Post a Project",
    POST_A_PROJECT_HOURLY: "Post a Project [Hourly]",
    POST_A_PROJECT_MILESTONE: "Post a Project [Milestone]",
    POST_A_PROJECT_INOFFICE: "Post a Project [In Office]",
    POST_A_JOB: "Post a Job",
    POWERFUL_SECURITY_TITLE: "Powerful Security on file management",
    POWERFUL_SECURITY_FIRST: "유료사용자의 경우 정글웍스가 등록한 특허기능으로 지정된 중요한 파일은 재택 근무시에도 지정컴퓨터 이외에서는 오픈과 공유가 불가능합니다.",
    POWERFUL_SECURITY_SECOND: "모바일 메신저의 경우 업무용과 개인용 메신저 구별하고 업무마감시 근무자의 개인 사생활이 철저히 보호됩니다.",
    PROJECT_SEARCH: "Project Search",
    REPORTS: "Reports",
    REUSING_EXISTING_A_POST: "Reusing an existing post",
    REQUIRED_MESSAGE: "Sorry! this field is required.",
    REVIEW_TEXT: "Review",
    SAVE_N_CONTINUE: "Save & Continue",
    SELECT_PROJECTY_TYPE: "Select a project type",
    SEOUL_TEXT: "Seoul",
    SERVICES: "Services",
    SET_PRFERRED_CLIENT: "Set Preferred Client",
    SHORTLIST_TEXT: "Short List",
    SIGNUP: "Sign up",
    SUBMITTED_WORKS: "Submitted Works",
    TARGET_COMPLETION: "Target Completion",
    TOTAL_TEXT: "Total",
    TRANSACTION: "My Transaction",
    TRANSLATION: "Translation",
    TRUSTABLE_FIRST: "필요시 업무자의 업무내용을 외부에서 즉시 확인이 가능함으로 부족한 소통으로 인한 잘못된 업무의 방향을 즉시 수정요구가 가능하여 이에따른 시간의 낭비를 방지할수 있습니다.",
    TRUSTABLE_SECOND: "정글웍스에 등록된 근무자의 리모트 컴퓨터에 연결되어 업무의 신뢰성을 높이고 인공지능이 근무활동을 평가하여 업무 효율을 극대화합니다. ",
    TUTORIAL_TEXT: "On/Offline Tutorial",
    TRUSTABLE_TITLE: "Trustable and Reliable",
    ULTIMATE_SOLUTION: "The Ultimate Solution for the Untact Working Environment",
    VIEW_MORE: "View More",
    WEB_DEVELOPMENT: "Web/Software",
    WORK_AT_OFFICE: "Work At Office",
    WORK_DETAIL: "Work Detail",
    WORK_WITH_MANAGER: "Manager",

};

export const MainTextKorean = {
    ACCOUNTING_TEXT: "세무/회계",
    ADD_MORE_SERVICES: "서비스 추가",
    ADMIN: "사무보조",
    ALL_FREELANCERS: "전체 프리랜서",
    ALL_PROJECTS: "전체 프로젝트",
    APP_DEVELOPMENT: "앱/소프트웨어",
    APPLICANTS_TEXT: "지원자",
    AWARDS_TEXT: "상금",
    BANNER_MAIN_FIRST: "정글웍스는 시간의 가치를",
    BANNER_MAIN_SECOND: "소중하게 생각합니다.",
    BANNER_MAIN_THIRD: "정글웍스에서는 프로젝트의 도급 발주는 물론 시간제 고용과 재택 또는 재택과 출근의 혼용된 방법으로 업무가 가능하여  고용인에게는 업무효율의 극대화를 프리랜서에게는 시간의 가치를 제공합니다.",
    BANNER_MAIN_FORTH: "관리 프로그램을 활용하시면 실시간 채팅 및 파일 업무관리 관리 다양한 관리툴을 무료로 편리하게 이용하실수 있습니다.",
    BLIND_TEXT: "블라인드",
    CAPTURED_VIEW: "업무 사진",
    CANCEL_TEXT: "취소",
    CANDIDATES_TEXT: "지원자",
    CATEGORY_TEXT: "카테고리",
    CHANNEL: "채널",
    CLIENT_INFO: "클라이언트 정보",
    COMMUNITY: "커뮤니티",
    COMPLETED_TEXT: "프로젝트 완료",
    CONFIRM_CONTEST: "컨테스트 설정",
    CONFIRM_PROJECT: "프로젝트 확인!",
    CONFIRM_MILESTONE: "마일스톤 확인!",
    CONFIRM_INOFFICE: "사무실에서 확인!",
    CONFIRM_HOURLY: "시간별 확인!",

    COMMUNICATION_MANAGER: "커뮤니케이션 매니저",
    CONTACT_US: "문의하기",
    CONTEST: "컨테스트",
    CONTEST_DETAIL: "컨테스트 상세정보",
    CONTRACT_HISTORY: "프로젝트 히스토리",
    CREATE_A_NEW_POST: "신규 포스트 등록",
    CUSTOMER_SERVICE: "고객센터",
    DAYS_TEXT: "일",
    DAYS_LEFT: "일 남음",
    DESIGN_CONTEST: "디자인 콘테스트",
    DESIGN_TEXT: "디자인",
    DEACTIVATE_TEXT: "비활성화",
    DISPUTE: "분쟁",
    DUE_DATE: "지원 마감일",
    ENGINEERING_TEXT: "기술/설계",
    ENGLISH: "ENGLISH",
    END_SOON: "마감임박순",
    EXTEND_DUE_DATE: "마감일 연장",
    EVALUATION: "프로젝트 평가",
    FEEDBACK: "피드백 & 클레임",
    FLEXIBILITY_FIRST: "프로젝트별, 시간제 그리고 전체 또는 부분 상주업무 또는 이를 혼합하여 업무를 협의할수 있습니다.",
    FLEXIBILITY_SECOND: "외부 프리랜서는 물론 기존의 근무자를 본 시스템에 적용하여 유연하게 재택근무와 내부근무를 동시에 관리할수 있습니다.",
    FLEXIBILITY_TITLE: "업무 유연성을 제공합니다.",
    FREELANCER: "프리랜서",
    FREELANCER_REGISTRATION: "프리랜서 등록",
    HEADHUNTING_MANAGER: "헤드헌팅 매니저",
    HELP_CENTER: "헬프 센터",
    HELP_DETAIL: "헬프 상세 페이지",
    HIGH_BUDGET: "높은 예산순",
    HOW_IT_WORKS: "사용방법",
    HOURLYNOFFICE: "시간제 및 상주혼합",
    HOURLY_TEXT: "시간제",
    HOURLY_REPORT: "업무 보고서 [시간제]",
    HOURLY_DETAIL: "시간제 세부 정보",
    HOURLY_WORK: "시간제 업무",
    HOURLY_VIEW:"시간별보기",
    IN_OFFICE: "상주업무",
    IN_OFFICE_DETAIL:"사무실에서",
    INTERNATIONAL_TRADE: "무역사무",
    INVOICE: "인보이스",
    INVOICE_DETAIL: "인보이스 상세",
    JAPANESE: "日本語",
    JOBS_NEARBY: "주변 프로젝트",
    KOREAN: "한국어",
    LEGAL_ASSITANCE: "법률보조",
    LOGIN: "로그인",
    LOGO_CONTEST: "로고 컨테스트",
    LOW_BUDGET: "낮은 예산순",
    LANGAUGE: "언어선택",
    LAST_ACTIVITY: "최근활동",
    MARKETING_TEXT: "마케팅/홍보",
    MILESTONE_DETAIL: "마일스톤 세부 정보",
    MILESTONE_TEXT: "마일스톤",
    MILESTONE_VIEW:"마일스톤보기",
    MILESTONE_REPORT:"마일스톤 보고서",
    MY_CLIENT: "마이 클라이언트",
    MY_CONTEST: "마이 컨테스트",
    MY_COUPON: "마이 쿠폰",
    MY_CREDIT: "마이 크레딧",
    MY_FREELANCERS: "마이 프리랜서",
    MY_PROJECT: "마이 프로젝트",
    MY_PROJECTS: "내 프로젝트",
    MY_PROPOSAL: "내 지원목록",
    MY_REGION: "내 주변 지역",
    MY_REPORTS: "마이 리포트",
    ONGOING_PROJECT: "진행중인 프로젝트",
    PAYMENT_CONFIRMATION_TYPE: "지불확정 타입",
    PLANNING: "기획/글쓰기",
    POST_A_JOB: "채용 정보 게시",
    POST_A_PROJECT: "프로젝트 게시",
    POST_A_PROJECT_HOURLY: "프로젝트 게시 [시간제 고용]",
    POST_A_PROJECT_MILESTONE: "프로젝트 게시 [마일스톤]",
    POST_A_PROJECT_INOFFICE: "프로젝트 게시 [상주]",
    POWERFUL_SECURITY_TITLE: "외부누출이 불가능한 강력한 파일관리",
    POWERFUL_SECURITY_FIRST: "유료사용자의 경우 정글웍스가 등록한 특허기능으로 지정된 중요한 파일은 재택 근무시에도 지정컴퓨터 이외에서는 오픈과 공유가 불가능합니다.",
    POWERFUL_SECURITY_SECOND: "모바일 메신저의 경우 업무용과 개인용 메신저 구별하고 업무마감시 근무자의 개인 사생활이 철저히 보호됩니다.",
    PHOTO_VIDEO: "비디오/사진 편집",
    PACKAGE_DESIGN: "패키지 디자인",
    PRIVATE_TEXT: "개별",
    PROMOTION_TEXT: "프로모션",
    PREFERRED_DESIGN: "선호 디자인",
    PROFESSION_TEXT: "업종 분류",
    PROJECT: "프로젝트",
    PROJECT_BLOG: "프로젝트 게시판",
    PROJECT_BUDGET: "프로젝트 예산",
    PROJECT_NO: "프로젝트 NO.",
    PROJECT_SEARCH: "프로젝트 선택",
    PROJECT_TITLE: "프로젝트 타이틀",
    REPORTS: "리포트",
    REUSING_EXISTING_A_POST: "기존 포스트를 활용",
    REVIEW_TEXT: "리뷰",
    SAVE_N_CONTINUE: "저장후 계속",
    SELECT_PROJECTY_TYPE: "프로젝트 타입을 선택하세요",
    SEOUL_TEXT: "서울",
    SERVICES: "서비스",
    SET_PRFERRED_CLIENT: "선호고객으로 저장",
    SHORTLIST_TEXT: "최종 후보자",
    TARGET_COMPLETION: "목표 완료일",
    TOTAL_TEXT: "전체",
    TRANSACTION: "거래내역",
    TRANSLATION: "통번역",
    TRUSTABLE_FIRST: "필요시 업무자의 업무내용을 외부에서 즉시 확인이 가능함으로 부족한 소통으로 인한 잘못된 업무의 방향을 즉시 수정요구가 가능하여 이에따른 시간의 낭비를 방지할수 있습니다.",
    TRUSTABLE_SECOND: "정글웍스에 등록된 근무자의 리모트 컴퓨터에 연결되어 업무의 신뢰성을 높이고 인공지능이 근무활동을 평가하여 업무 효율을 극대화합니다. ",
    TUTORIAL_TEXT: "온/오프라인 강의",
    TRUSTABLE_TITLE: "신뢰성있는 근무환경을 제공",
    SIGNUP: "가입하기",
    SUBMITTED_WORKS: "제출된 작업",
    ULTIMATE_SOLUTION: "언택트 업무환경의 최적의 솔루션을 제공합니다.",
    VIEW_MORE: "더보기",
    WEB_DEVELOPMENT: "웹/소프트웨어",
    WORK_AT_OFFICE: "상주업무",
    WORK_DETAIL: "업무상세",
    WORK_WITH_MANAGER: "담당 매니저"
};

export const MainTextJapanese = {
    PROJECT: "事業",
    MY_PROJECTS: "私のプロジェクト",
    POST_A_PROJECT: "プロジェクトを投稿する",
    FREELANCER: "フリーランサー",
    ALL_FREELANCERS: "すべてのフリーランサー",
    MY_FREELANCERS: "私のフリーランサー",
    HOW_IT_WORKS: "使い方",
    CONTEST: "コンテスト",
    HOURLY_WORK: "時給",
    WORK_AT_OFFICE: "オフィスで働く",
    DISPUTE: "紛争",
    MY_CREDIT: "私のクレジット",
    REPORTS: "報告書",
    TRANSACTION: "トランザクション",
    MY_COUPON: "マイクーポン",
    SERVICES: "サービス",
    COMMUNICATION_MANAGER: "コミュニケーションマネージャー",
    HEADHUNTING_MANAGER: "ヘッドハンティングマネージャー",
    COMMUNITY: "コミュニティ",
    CHANNEL: "チャネル",
    HELP_CENTER: "ヘルプセンター",
    CONTACT_US: "お問い合わせ",
    LOGIN: "ログインする",
    SIGNUP: "サインアップ",
    POST_A_JOB: "仕事を投稿する",
    LANGAUGE: "言語",
    ENGLISH: "英語",
    KOREAN: "韓国語",
    JAPANESE: "日本人",

};